/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.academysystem.view;

import br.com.academysystem.bancodedados.FuncionarioDAO;
import br.com.academysystem.entidades.Funcionario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author guilh
 */
public class ControleFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarFuncionarios
     */
    public ControleFuncionario() {
        initComponents();
        DefaultTableModel modeloTabela = (DefaultTableModel) listaFuncionarios.getModel();
        listaFuncionarios.setRowSorter(new TableRowSorter(modeloTabela));
        readDadosTabela();
    }

    public final void readDadosTabela() {
        DefaultTableModel modeloTabela = (DefaultTableModel) listaFuncionarios.getModel();
        SimpleDateFormat dataNascimento = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat dataCadastro = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat dataVencimento = new SimpleDateFormat("dd/MM/yyyy");
        FuncionarioDAO dao = new FuncionarioDAO();
        modeloTabela.setNumRows(0);
        dao.listarFuncionarios().stream().forEach((Funcionario funcionario) -> {
            modeloTabela.addRow(new Object[]{
                funcionario.getId(),
                funcionario.getNome(),
                funcionario.getCpf(),
                dataNascimento.format(funcionario.getDataDeNascimento().getTime()),
                funcionario.getSexo(),
                funcionario.getPeso(),
                funcionario.getTelefone(),
                funcionario.getTipoSanguineo(),
                funcionario.getSalario(),
                dataCadastro.format(funcionario.getDataDeAdimissao().getTime()),
                dataVencimento.format(funcionario.getDataDePagamento().getTime()),});
        });

    }

    public final void buscarDadosTabela(String nome) {
        DefaultTableModel modeloTabela = (DefaultTableModel) listaFuncionarios.getModel();
        SimpleDateFormat dataNascimento = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat dataCadastro = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat dataVencimento = new SimpleDateFormat("dd/MM/yyyy");
        FuncionarioDAO dao = new FuncionarioDAO();
        modeloTabela.setNumRows(0);
        dao.buscarFuncionarios(nome).stream().forEach((Funcionario funcionario) -> {
            modeloTabela.addRow(new Object[]{
                funcionario.getId(),
                funcionario.getNome(),
                funcionario.getCpf(),
                dataNascimento.format(funcionario.getDataDeNascimento().getTime()),
                funcionario.getSexo(),
                funcionario.getPeso(),
                funcionario.getTelefone(),
                funcionario.getTipoSanguineo(),
                funcionario.getSalario(),
                dataCadastro.format(funcionario.getDataDeAdimissao().getTime()),
                dataVencimento.format(funcionario.getDataDePagamento().getTime()),});
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        peso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tiposangue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        salario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        sexo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dataAdmissao = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dataDePagamento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nomebusca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFuncionarios = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cpf = new javax.swing.JFormattedTextField();
        datanas = new javax.swing.JFormattedTextField();
        numerotelefone = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Nome:");

        tiposangue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiposangueActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF:");

        jLabel3.setText("Data de Nascimento:");

        jLabel7.setText("Numero de Telefone:");

        jLabel8.setText("Salario:");

        salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Sexo:");

        jLabel5.setText("Peso:");

        jLabel6.setText("Tipo Sanguíneo:");

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        jLabel9.setText("Id:");

        id.setEditable(false);

        jLabel10.setText("Data de Admissão:");

        dataAdmissao.setEditable(false);

        jLabel11.setText("Data de Paganto:");

        dataDePagamento.setEditable(false);

        jLabel12.setText("Buscar por nome:");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Alterar Dados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        listaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "CPF", "Data de Nascimento", "Sexo", "Peso", "Telefone", "Tipo Sanguineo", "Salário", "Data de Admissão", "Data de Pagamentos"
            }
        ));
        listaFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaFuncionarios);

        jButton4.setText("jButton4");

        jButton5.setText("Cadastrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            datanas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            numerotelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomebusca, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(148, 148, 148)
                                        .addComponent(jLabel4)
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(cpf)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel7))
                                    .addComponent(datanas, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tiposangue, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(numerotelefone)
                                        .addGap(18, 18, 18)
                                        .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(dataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)
                            .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tiposangue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(datanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)
                            .addComponent(numerotelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(nomebusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiposangueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiposangueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiposangueActionPerformed

    private void salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.buscarDadosTabela(nomebusca.getText());         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Funcionario funcionario = new Funcionario();
                    funcionario.setId(Integer.parseInt(id.getText()));
                    funcionario.setNome(nome.getText());
                    funcionario.setCpf(cpf.getText());
                    funcionario.setDataDePagamento(Calendar.getInstance());
                    funcionario.setDataDeAdimissao(Calendar.getInstance()); // QUERO QUE SOME TRINTA DIAS ATRAVES DA DATA LOCALL E ADICIONE A DATA DE VENCIMETO
                    
                    Calendar dataNascimento = null;
                    
                    try {
                        java.util.Date date = new SimpleDateFormat("dd/MM/yyyy").parse(datanas.getText());
                        dataNascimento = Calendar.getInstance();
                        dataNascimento.setTime(date);
                    } catch (ParseException e) {
                        JOptionPane.showMessageDialog(null, "Erro na Conversão da Data");
                        return;
                    }
                    
                    funcionario.setDataDeNascimento(dataNascimento);
                    double pesoemdouble = Double.parseDouble(peso.getText());
                    funcionario.setSalario(Double.parseDouble(salario.getText()));
                    funcionario.setPeso(pesoemdouble);
                    funcionario.setSexo(sexo.getText());
                    funcionario.setTipoSanguineo(tiposangue.getText());
                    funcionario.setTelefone(numerotelefone.getText());// TODO add your handling code here:
                    
                    FuncionarioDAO dao = new FuncionarioDAO();
                    dao.alteraFuncionario(funcionario);
                    readDadosTabela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void listaFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaFuncionariosMouseClicked
            // TODO add your handling code here:
        if (listaFuncionarios.getSelectedRow() != -1) {
            id.setText(listaFuncionarios.getValueAt(listaFuncionarios.getSelectedRow(), 0).toString());
            nome.setText(listaFuncionarios.getValueAt(listaFuncionarios.getSelectedRow(), 1).toString());
            cpf.setText(listaFuncionarios.getValueAt(listaFuncionarios.getSelectedRow(), 2).toString());
            datanas.setText(listaFuncionarios.getValueAt(listaFuncionarios.getSelectedRow(), 3).toString());
            sexo.setText(listaFuncionarios.getValueAt(listaFuncionarios.getSelectedRow(), 4).toString());
            peso.setText(listaFuncionarios.getValueAt(listaFuncionarios.getSelectedRow(), 5).toString());
            numerotelefone.setText(listaFuncionarios.getValueAt(listaFuncionarios.getSelectedRow(), 6).toString());
            tiposangue.setText(listaFuncionarios.getValueAt(listaFuncionarios.getSelectedRow(), 7).toString());
            salario.setText(listaFuncionarios.getValueAt(listaFuncionarios.getSelectedRow(), 8).toString());
            dataAdmissao.setText(listaFuncionarios.getValueAt(listaFuncionarios.getSelectedRow(), 9).toString());
            dataDePagamento.setText(listaFuncionarios.getValueAt(listaFuncionarios.getSelectedRow(), 10).toString());
        }
    }//GEN-LAST:event_listaFuncionariosMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 if (listaFuncionarios.getSelectedRow() != -1) {
            Funcionario funcionario = new Funcionario();
            int idCliente = Integer.parseInt(id.getText());
            funcionario.setId(idCliente);
            FuncionarioDAO dao = new FuncionarioDAO();
            dao.excluirFuncionario(funcionario);
            readDadosTabela();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    Funcionario funcionario = new Funcionario();
                    funcionario.setNome(nome.getText());
                    funcionario.setCpf(cpf.getText());
                    funcionario.setDataDePagamento(Calendar.getInstance());
                    funcionario.setDataDeAdimissao(Calendar.getInstance()); // QUERO QUE SOME TRINTA DIAS ATRAVES DA DATA LOCALL E ADICIONE A DATA DE VENCIMETO
                    
                    Calendar dataNascimento = null;
                    
                    try {
                        java.util.Date date = new SimpleDateFormat("dd/MM/yyyy").parse(datanas.getText());
                        dataNascimento = Calendar.getInstance();
                        dataNascimento.setTime(date);
                    } catch (ParseException e) {
                        JOptionPane.showMessageDialog(null, "Erro na Conversão da Data");
                        return;
                    }
                    
                    funcionario.setDataDeNascimento(dataNascimento);
                    double pesoemdouble = Double.parseDouble(peso.getText());
                    funcionario.setSalario(Double.parseDouble(salario.getText()));
                    funcionario.setPeso(pesoemdouble);
                    funcionario.setSexo(sexo.getText());
                    funcionario.setTipoSanguineo(tiposangue.getText());
                    funcionario.setTelefone(numerotelefone.getText());// TODO add your handling code here:
                    
                    FuncionarioDAO dao = new FuncionarioDAO();
                    dao.adicionaFuncionario(funcionario);
                    readDadosTabela();// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JTextField dataAdmissao;
    private javax.swing.JTextField dataDePagamento;
    private javax.swing.JFormattedTextField datanas;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaFuncionarios;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomebusca;
    private javax.swing.JFormattedTextField numerotelefone;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField salario;
    private javax.swing.JTextField sexo;
    private javax.swing.JTextField tiposangue;
    // End of variables declaration//GEN-END:variables
}
