/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.academysystem.view;

import br.com.academysystem.bancodedados.ClienteDAO;
import br.com.academysystem.entidades.Cliente;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public class ControleCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaClientes
     */
    public ControleCliente() {
        initComponents();
        DefaultTableModel modeloTabela = (DefaultTableModel) listaClientes.getModel();
        listaClientes.setRowSorter(new TableRowSorter(modeloTabela));
        this.readDadosTabela();
    }

    public final void readDadosTabela() {
        DefaultTableModel modeloTabela = (DefaultTableModel) listaClientes.getModel();
        SimpleDateFormat dataNascimento = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat dataCadastro = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat dataVencimento = new SimpleDateFormat("dd/MM/yyyy");
        ClienteDAO dao = new ClienteDAO();
        modeloTabela.setNumRows(0);
        dao.listarCliente().stream().forEach((Cliente cliente) -> {
            modeloTabela.addRow(new Object[]{
                cliente.getId(),
                cliente.getNome(),
                cliente.getCpf(),
                dataNascimento.format(cliente.getDataDeNascimento().getTime()),
                cliente.getSexo(),
                cliente.getPeso(),
                cliente.getTelefone(),
                cliente.getTipoSanguineo(),
                dataCadastro.format(cliente.getDataDeCadastro().getTime()),
                dataVencimento.format(cliente.getDataDeVencimento().getTime()),
            });
        });

    }

    public final void buscarDadosTabela(String nome) {
        DefaultTableModel modeloTabela = (DefaultTableModel) listaClientes.getModel();
        SimpleDateFormat dataNascimento = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat dataCadastro = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat dataVencimento = new SimpleDateFormat("dd/MM/yyyy");
        ClienteDAO dao = new ClienteDAO();
        modeloTabela.setNumRows(0);
        dao.buscaCliente(nome).stream().forEach((Cliente cliente) -> {
            modeloTabela.addRow(new Object[]{
                cliente.getId(),
                cliente.getNome(),
                cliente.getCpf(),
                dataNascimento.format(cliente.getDataDeNascimento().getTime()),
                cliente.getSexo(),
                cliente.getPeso(),
                cliente.getTelefone(),
                cliente.getTipoSanguineo(),
                dataCadastro.format(cliente.getDataDeCadastro().getTime()),
                dataVencimento.format(cliente.getDataDeVencimento().getTime()),
            });
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inserirnome = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaClientes = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        datanascimento = new javax.swing.JTextField();
        sexo = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        tiposangue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        datapagamento = new javax.swing.JTextField();
        datavencimento = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Clientes Cadastrados");

        jLabel1.setText("Pesquisar Clientes: ");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        listaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "CPF", "Data de Nascimento", "Sexo", "Peso", "Telefone", "Tipo Sanguíneo", "Data de Pagamento", "Data de Vencimento"
            }
        ));
        listaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaClientes);
        if (listaClientes.getColumnModel().getColumnCount() > 0) {
            listaClientes.getColumnModel().getColumn(8).setResizable(false);
            listaClientes.getColumnModel().getColumn(9).setResizable(false);
        }

        jLabel6.setText("Tipo Sanguíneo:");

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });

        tiposangue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiposangueActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("CPF:");

        jLabel4.setText("Data de Nascimento");

        jLabel5.setText("Sexo:");

        jLabel7.setText("Peso:");

        jLabel8.setText("ID:");

        id.setEditable(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jLabel9.setText("Data de Pagamento:");

        jLabel10.setText("Data de Vencimento:");

        datapagamento.setEditable(false);

        datavencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datavencimentoActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        alterar.setText("Alterar Dados");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        jLabel11.setText("Numero Telefone:");

        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        jButton3.setText("Cadastrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inserirnome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(148, 148, 148)
                                        .addComponent(jLabel5)
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel4))
                                .addGap(57, 57, 57)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cpf)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(datapagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(datavencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(telefone))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datanascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(tiposangue, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(alterar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datanascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tiposangue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alterar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datapagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datavencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(inserirnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    private void tiposangueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiposangueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiposangueActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void datavencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datavencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datavencimentoActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
                    cliente.setId(Integer.parseInt(id.getText()));
                    cliente.setNome(nome.getText());
                    cliente.setCpf(cpf.getText());
                    cliente.setDataDeCadastro(Calendar.getInstance());
                    cliente.setDataDeVencimento(Calendar.getInstance()); // QUERO QUE SOME TRINTA DIAS ATRAVES DA DATA LOCALL E ADICIONE A DATA DE VENCIMETO
                    
                    Calendar dataNascimento = null;
                    
                    try {
                        java.util.Date date = new SimpleDateFormat("dd/MM/yyyy").parse(datanascimento.getText());
                        dataNascimento = Calendar.getInstance();
                        dataNascimento.setTime(date);
                    } catch (ParseException e) {
                        JOptionPane.showMessageDialog(null, "Erro na Conversão da Data");
                        return;
                    }
                    
                    cliente.setDataDeNascimento(dataNascimento);
                    double pesoemdouble = Double.parseDouble(peso.getText());
                    cliente.setPeso(pesoemdouble);
                    cliente.setSexo(sexo.getText());
                    cliente.setTipoSanguineo(tiposangue.getText());
                    cliente.setTelefone(telefone.getText());// TODO add your handling code here:
                    
                    ClienteDAO dao = new ClienteDAO();
                    dao.alterarCliente(cliente);
                    this.readDadosTabela();
                    
             
    }//GEN-LAST:event_alterarActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (listaClientes.getSelectedRow() != -1) {
            Cliente cliente = new Cliente();
            int idCliente = Integer.parseInt(id.getText());
            cliente.setId(idCliente);
            ClienteDAO dao = new ClienteDAO();
            dao.excluirCliente(cliente);
            readDadosTabela();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        this.buscarDadosTabela(inserirnome.getText());        // TODO add your handling code here:

    }//GEN-LAST:event_buscarActionPerformed

    private void listaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaClientesMouseClicked
        // TODO add your handling code here:
        if (listaClientes.getSelectedRow() != -1) {
            id.setText(listaClientes.getValueAt(listaClientes.getSelectedRow(), 0).toString());
            nome.setText(listaClientes.getValueAt(listaClientes.getSelectedRow(), 1).toString());
            cpf.setText(listaClientes.getValueAt(listaClientes.getSelectedRow(), 2).toString());
            datanascimento.setText(listaClientes.getValueAt(listaClientes.getSelectedRow(), 3).toString());
            sexo.setText(listaClientes.getValueAt(listaClientes.getSelectedRow(), 4).toString());
            peso.setText(listaClientes.getValueAt(listaClientes.getSelectedRow(), 5).toString());
            telefone.setText(listaClientes.getValueAt(listaClientes.getSelectedRow(), 6).toString());
            tiposangue.setText(listaClientes.getValueAt(listaClientes.getSelectedRow(), 7).toString());
            datapagamento.setText(listaClientes.getValueAt(listaClientes.getSelectedRow(), 8).toString());
            datavencimento.setText(listaClientes.getValueAt(listaClientes.getSelectedRow(), 9).toString());
        }
    }//GEN-LAST:event_listaClientesMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                Cliente cliente = new Cliente();
                    cliente.setNome(nome.getText());
                    cliente.setCpf(cpf.getText());
                    cliente.setDataDeCadastro(Calendar.getInstance());
                    cliente.setDataDeVencimento(Calendar.getInstance()); // QUERO QUE SOME TRINTA DIAS ATRAVES DA DATA LOCALL E ADICIONE A DATA DE VENCIMETO
                    
                    Calendar dataNascimento = null;
                    
                    try {
                        java.util.Date date = new SimpleDateFormat("dd/MM/yyyy").parse(datanascimento.getText());
                        dataNascimento = Calendar.getInstance();
                        dataNascimento.setTime(date);
                    } catch (ParseException e) {
                        JOptionPane.showMessageDialog(null, "Erro na Conversão da Data");
                        return;
                    }
                    
                    cliente.setDataDeNascimento(dataNascimento);
                    double pesoemdouble = Double.parseDouble(peso.getText());
                    cliente.setPeso(pesoemdouble);
                    cliente.setSexo(sexo.getText());
                    cliente.setTipoSanguineo(tiposangue.getText());
                    cliente.setTelefone(telefone.getText());// TODO add your handling code here:
                    
                    ClienteDAO dao = new ClienteDAO();
                    dao.adicionaCliente(cliente);
                    readDadosTabela();
                     // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField datanascimento;
    private javax.swing.JTextField datapagamento;
    private javax.swing.JTextField datavencimento;
    private javax.swing.JTextField id;
    private javax.swing.JTextField inserirnome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaClientes;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField sexo;
    private javax.swing.JTextField telefone;
    private javax.swing.JTextField tiposangue;
    // End of variables declaration//GEN-END:variables
}
